### ISSUE TITLE
Stackset or not?

### ISSUE THREAD

**Issue by Ongy** [Ongy/waymonad#1]
A core component of xmonad is the StackSet. It's what Layouts and interaction with the WM is based on.

The question is, do we want to reimplement the stackset?

Pro:
* Easy to port Layouts
* Battle proven
* As it is in xmonad

Cons:
* somewhat limited, not really the way humans interact with the desktop
* We have the chance to build on the experience from it

**Comment by Ongy** [comment]
Just to keep this updated:
I went and implemented something that mostly resembled the stackset to make my basic layouts/testing.

The main reason I'm going away from this is multi-seat.
The Stackset has inherently *1* focused window on each workspace.
With multiseat we want to have 1 focused window / seat for each workspace, which makes things significantly more complicated

**Comment by Ongy** [comment]
The current situation is `[Maybe Seat, View]`
This *may* change in the future, but for now I think two  main properties are going to stay.
  * Ordered Set
  * Seat tags for focus

If things change, it's going to be mostly to optimize memory or modifications

**Comment by jfeick** [comment]
I personally think it would be a good idea to ditch the existing StackSet.hs from XMonad completely in favor of a sane window datatype. I would like to see sane handling of floating clients and "memorization" of their place in the "StackSet".

**Comment by roosemberth** [comment]
Hi,

I remember reading a couple of discussions about "static" windows (that is windows available on multiple workspaces at the same time) where they stated that stackset was one of the main problems to implement it. I think the same could be achieved with placeholders and then show the texture over it.

How to you plan to manage static windows?
How to you plan to handle the case where there are multiple screens with different DPI showing the same window?

**Comment by Ongy** [comment]
We are not going to get a sane window type. Sorry to disappoint you =.=
The reason being: There's currently 3 shells implemented on the `wlroots` side (2 of them work here), and we need at least the 2 I already did.
They are not the same and will never be. Currently it's `xwayland` and `xdg_shell_v6` that I consider crucial, we may get more.
I'm comfortable with *some* assumptions and defaulting where it's not supported, but I don't want to build an overly sophisticated general window type.
This is currently the [View](https://github.com/Ongy/waymonad/blob/master/src/View.hs#L56).
I expect the view to get a few more events/management functionality, but I don't think the idea of a general window will be expanded far over this. Simply because I don't think the shells are compatible, and we will have a few window types in the end.


As to static windows: I am somewhat convinced I did that before without major issues, BUT I couldn't get them to display twice, which afaik is an X server limitation, not xmonad.
As the small screenshot on the readme shows, this is very possible here, at least in a toy example.

For the more interesting cases there's multiple things possible.
 * Tile it multiple times
 * Float it consistently (current way floats work) / xmonad unmanaged windows

For tiling multiple times, things are complicated.
There's not just the question about scaling, there's also one about sizing in general.
My current plan is to implement this into copy views (probably a pseudo-shell in the end) and have the logic in those.

I haven't looked into the scaling yet, I'm currently waiting on a  `wlroots`-PR which reworkes the renderer so I don't feel particularily motivated to work on something that ties closly with the renderer before that's in.
But I have seen that they got it reasonably well done on the `rootston` (wlroots reference compositor) for floating windows between screens with different scaling, so I'm confident it's possible to do.

**Comment by Ongy** [comment]
@roosemberth btw. I had some fun and implemented `View.Proxy` there's a screenshot on the bottom.
This is the very basic version that doesn't try to negotiate resolutions or anything else, but just considers the first one the master, but it's fun to play with.

**Comment by Ongy** [comment]
On the original topic:

After getting bugged about this on IRC, I made the actual ViewSet implementation an argument to the `Way` Monad and created a couple of classes (can be seen in [ViewSet.hs](https://github.com/Ongy/waymonad/blob/master/src/ViewSet.hs)) that provide different capabilities interactions with the viewset can be based on.

The default one will be [XMonad.ViewSet](https://github.com/Ongy/waymonad/blob/master/src/XMonad/ViewSet.hs) for now, but I'm still open to change things.

**Comment by Ongy** [comment]
I've decided to keep this by now.
