### ISSUE TITLE
Configure with Haskell?

### ISSUE THREAD

**Issue by Ongy** [Ongy/waymonad#3]
One of the great strengths of xmonad is the possiblity to configure it in Haskell.
This allows to implement any extension and behavior as user configuration.

But this also pulls in the entire GHC ecosystem as runtime dependency and error messages can be a bit unintuitive.

I think we should try to implement a hybrid approach, providing a Haskell based configuration like xmonad has, but provide a text based configuration method for (at least core) modules.

**Comment by jfeick** [comment]
I second the hybrid approach.
I would suggest to provide a way to convert a basic configuration file similar to i3's configuration format (INI file format) to a xmonad.hs like file. This would make the window manager more approachable by i3/sway users (which imho make up the majority of tiling wm users) and eventually raise interest to configure the wm using the haskell configuration file.

**Comment by lkjell** [comment]
If the config is similar to i3/sway. I.e text based. Then why bother to use xmonad when you could also configure the same with i3? 

In any cases xmonad strength is not its weakness. The weakness is perhaps lack of examples and too much variety to just configure one thing. 

Some points that may improve more.
* sane default configuration. (What happen to bluetile?)
* update examples and make them consistent with each other. That is you can copy and paste from different examples without changing too much of the code.
* api have examples usage too.

**Comment by Ongy** [comment]
I'd say I have decided on this.
`waymonad` will be leaning (even more) towards a library than binary like `xmonad` does.

But I have [a text basec config system](https://github.com/Ongy/waymonad/tree/master/src/Config) which can be completly detached from the core, and may be split out into a seperate package in future.

The only thing that stands to be decided is a policy if people will be required to provide code for this when they want to get something upstreamed, but that will happen once it's fully built.
