### ISSUE TITLE
wayland clients dont get correct screen dimensions

### ISSUE THREAD

**Issue by fiete201** [Ongy/waymonad#33]
Im on master now.
All wayland clients behave as if they were 4 times to big so one only sees the upper left quarter of the window.

How to reproduce:
Build master
Start for example xfce4-terminal or gajim and see that you get only the upper left quarter of the window.

**Comment by fiete201** [comment]
The window itself gets drawn correctly on the external unscaled display but context menus are also drawn too big and text inside is unreadable because its bigger than the box of the menu itself

**Comment by Ongy** [comment]
https://github.com/waymonad/waymonad/commit/7f244e1686afecca968346a79ebc3541669c148e should fix this.
Testing appreciated.

**Comment by fiete201** [comment]
Yes this is fixed now. Thanks!
