### ISSUE TITLE
Crash on start (since 3026fd0)

### ISSUE THREAD

**Issue by willat8** [Ongy/waymonad#38]
I'm building with the latest wlroots and the Haskell 8.6.3 bundle (docker).
With a very lightly modified config https://github.com/willat8/waymonad-config/blob/master/my/Main.hs

When launching waymonad I am receiving

`error, called at src/Graphics/Wayland/WlRoots/Input.hsc:61:21 in hsroots-0.1.0.0-inplace:Graphics.Wayland.WlRoots.Inpu(seatOutChangeEvtPre = Nothing, seatOutChangeEvtNew = Just eDP-1)`

Followed by waymonad exiting.

**Comment by Ongy** [comment]
should be fixed with d425ffc
you have something that comes up as "switch" input device, that won't work for now, but I added a stub so it won't error out.
Please confirm and close issue.

**Comment by willat8** [comment]
Thanks, working great now!
