### ISSUE TITLE
Fuse?

### ISSUE THREAD

**Issue by Ongy** [Ongy/waymonad#5]
So I had a silly little idea.

`waymonad` will be responsible for a little more than `xmonad`.
We control outputs, their modes, input devices, seats etc.
We will hopefully get some default/shared tools for at least niche compositors and with some luck even the big ones.

But
  * This could take a while
  * Maybe we don't like those tools

So something custom to this project may be required. I don't feel like implementing much of an IPC mechanism, partially because of the usability implications.

What do you think about exposing a FUSE filesystem similar to `/sys/` on linux where we can bind devices to seats, list/set output modes and positions etc.

**Comment by Profpatsch** [comment]
May want to look at [9p](https://en.wikipedia.org/wiki/9P_(protocol)). There seem to exists two hackage packages that could make implementing that easy: https://hackage.haskell.org/packages/search?terms=9p

**Comment by Ongy** [comment]
While I appreciate the feedback (and do admire 9p) this "only" layers another protocol over fuse.
And I'm not sure I want to use non-standard (I consider fuse somewhat standard, on most systems) system dependencies in the compositor.


On the other hand, I started playing with tis idea and it's not all that bad (after building some abstractions): [Screenshot showing of fuse](https://i.imgur.com/ptvZAqg.png)

**Comment by roosemberth** [comment]
Maybe I'm not well-aware of how the shell protocols work nor the tools available to interact with it. But I think that having fs interactions would make scripting (ie. udev rules?) quite straightforward

**Comment by Ongy** [comment]
I don't (currently) intend this to be for scripting the entire UI, but to provide IPC that the xorg-server or xmonad provided.

This could probably be expanded to surface further internals, but for now I mainly intend it to configure things on the fly, that can't be configured with "proper" tools.

For example, we don't have an xrandr/arandr like tool yet. The protocol that should implement this, is currently in development. I have no idea when it will be done and I can integrate it, but I do feel like it's an important feature to set output modes at runtime.
Therefore I want to provide that feature over a custom IPC, which I wanted to look into fuse.
We can easily script it on the shell with this approach, but hopefully there will be cli/scriptable tools for the cross-compositor tools later (e.g. xrandr like functionality I'm likely to write if nobody else does).

If you are interested in this, do feel free to lay out some ideas how to design the file system for your needs. Currently I'm more looking into the whole thing than actually being settled on it, but I think it's a good idea (though it will of course be optional in the end).

**Comment by Ongy** [comment]
This is pretty much decided upon by now.
The "official", initial IPC implemented by me is a Fuse filesystem.
This can be disabled in 2 lines with the current code, and it should be easy to base a different IPC mechanism on the core hooks and basic layout from it.

The only thing I need to look into right now is whether I can run the logHook over it, but I don't mind if that's on another IPC solution (since it's strictly push output)
